namespace Hooks.Service.Infrastructure.Middleware.Models;

/// <summary>Model representing generic error</summary>
public class ErrorModel
{
    /// <summary>The HTTP status code generated by the server for this occurrence of the problem.</summary>
    public int Status { get; internal init; } = 400;

    /// <summary>
    /// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the
    /// problem, except for purposes of localization.
    /// </summary>
    public string Title { get; internal init; } = string.Empty;

    /// <summary>A human-readable explanation specific to this occurrence of the problem.</summary>
    public string Detail { get; internal init; } = string.Empty;

    /// <summary>A URI reference that identifies the problem type.</summary>
    public string Type { get; internal init; } = "about:blank";

    /// <summary>Creates a new instance of ErrorModel representing a given <see cref="Exception"/> object.</summary>
    /// <param name="exception">The exception.</param>
    public static ErrorModel FromException(Exception exception)
        => new()
        {
            Status = 500,
            Type = "http://reapit.hooks.service/problems/exception",
            Title = "An unexpected error has occurred",
            Detail = exception.Message
        };
}