using System.Text.Json.Serialization;

namespace Hooks.Service.Infrastructure.Middleware.Models;

/// <summary>Model representing generic error</summary>
public class ErrorModel
{
    /// <summary>The HTTP status code generated by the server for this occurrence of the problem.</summary>
    [JsonPropertyName("status")]
    public int Status { get; init; } = 500;

    /// <summary>
    /// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the
    /// problem, except for purposes of localization.
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; init; } = string.Empty;

    /// <summary>A human-readable explanation specific to this occurrence of the problem.</summary>
    [JsonPropertyName("detail")]
    public string Detail { get; init; } = string.Empty;

    /// <summary>A URI reference that identifies the problem type.</summary>
    [JsonPropertyName("type")]
    public string Type { get; init; } = string.Empty;

    /// <summary>Creates a new instance of ErrorModel representing a given <see cref="Exception"/> object.</summary>
    /// <param name="exception">The exception.</param>
    public static ErrorModel FromException(Exception exception)
        => new()
        {
            Status = 500,
            Title = "An unexpected error has occurred",
            Type = "http://reapit.hooks.service/problems/exception",
            Detail = exception.Message
        };
}