name: Build and test
on: [push]

jobs:
  build-solution:
    name: Test Hooks.sln
    runs-on: ubuntu-latest
    steps:
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: restore project
        run: dotnet restore ./src/Hooks.sln
      - name: build project
        run: dotnet build ./src/Hooks.sln --no-restore
      - name: test project
        run: dotnet test ./src/Hooks.sln --no-build --logger trx --results-directory test-results --collect:"xplat code coverage"
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/*.trx
      - name: generate code coverage report
        run: |
          mkdir code-coverage
          cp ./test-results/*/coverage.cobertura.xml ./test-results/coverage.cobertura.xml
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"test-results/coverage.cobertura.xml" -targetdir:"code-coverage" -reporttypes:Html
      - name: upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: code-coverage
